name: metameq
channels:
  - defaults
dependencies:
# NB: if changing here, also change the setup.py install_requires
  - python
  - click
  - pandas
  - openpyxl
  - pip
  - pyyaml
  - flake8
  - pep8
  - pytest
  - pip:
    - cerberus
